### ISSUE TITLE
Clear branches

### ISSUE THREAD

**Issue by slenderock** [r1dd1ck777/git-hotfix#2]
Probably, you know situation, when in your IDE displays all branches, that you has ever created.
I always fix it by typing:
`git branch --merged | grep -v \* | xargs git branch -D  `
and 
` git fetch -p `

Maybe need to add `hf clear-branches` command?
How do you think?

**Comment by ruslan-palahin** [comment]
Take a look at `hf delete-merged` - if works fine for me) 

Tested case: 
1. main branch (gitlab) - master
2. mode - hotfix

![selection_055](https://cloud.githubusercontent.com/assets/2765710/25186035/9f992c4c-2527-11e7-8d80-cd539e5daa74.png)

The benefit of `hf delete-merged` is deleting branches on remote as well as locally.
