### ISSUE TITLE
Ability to config hotfix mode

### ISSUE THREAD

**Issue by vborshchov** [r1dd1ck777/git-hotfix#4]
First of all thanks for great tool :+1:  It would be great to use custom branches for hotfix mode or feature mode. For example, in my project I have branch `staging` and want to use feature mode for `staging` branch but not `develop`(default branch name for now) for new feature.

**Comment by ruslan-palahin** [comment]
Great idea! Waiting for pull request :)

**Comment by ruslan-palahin** [comment]
Done in 2nd version!
